# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1632533336);
user_pref("app.update.lastUpdateTime.background-update-timer", 1632539089);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1632538969);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1632615915);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1632612449);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.parent_directory", "C:\\Users\\GAEL GARZA\\Videos\\lelseq\\Programs\\wrapperga\\GoAnimate-Wrapper-master\\main\\browser\\Brazilik\\Basilisk-Portable\\User\\Basilisk\\Profiles\\Default");
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "C:\\Users\\GAEL GARZA\\Videos\\lelseq\\Programs\\wrapperga\\GoAnimate-Wrapper-master\\main\\browser\\Brazilik\\Basilisk-Portable\\Downloads");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1632170442);
user_pref("browser.laterrun.bookkeeping.sessionCount", 22);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 42);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190912144529");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 15007);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190912144529");
user_pref("browser.startup.homepage_override.mstone", "4.4.1");
user_pref("browser.taskbar.lists.enabled", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"developer-button\",\"add-ons-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 0);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20210924);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_OS_ENUMERATED_PER_USER\":\"52.9.2019.09.12\",\"DEVTOOLS_OS_IS_64_BITS_PER_USER\":\"52.9.2019.09.12\",\"DEVTOOLS_SCREEN_RESOLUTION_ENUMERATED_PER_USER\":\"52.9.2019.09.12\"}");
user_pref("devtools.toolbar.visible", true);
user_pref("devtools.toolbox.selectedTool", "inspector");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 350);
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", 5);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.9.2019.09.12");
user_pref("extensions.lastAppVersion", "52.9.2019.09.12");
user_pref("extensions.lastPlatformVersion", "4.4.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/plugin");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Users\\\\GAEL GARZA\\\\Videos\\\\lelseq\\\\Programs\\\\wrapperga\\\\GoAnimate-Wrapper-master\\\\main\\\\browser\\\\Brazilik\\\\Basilisk-Portable\\\\Bin\\\\Basilisk\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"52.9.2019.09.12\",\"st\":1631297440186}}}");
user_pref("gfx.crash-guard.d3d11layers.appVersion", "52.9.2019.09.12");
user_pref("gfx.crash-guard.d3d11layers.deviceID", "0x954f");
user_pref("gfx.crash-guard.d3d11layers.driverVersion", "8.970.100.9001");
user_pref("gfx.crash-guard.d3d11layers.feature-d2d", true);
user_pref("gfx.crash-guard.d3d11layers.feature-d3d11", true);
user_pref("gfx.crash-guard.status.d3d11layers", 2);
user_pref("idle.lastDailyNotification", 1632539186);
user_pref("media.benchmark.vp9.fps", 49);
user_pref("media.benchmark.vp9.versioncheck", 3);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1632172947);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190912144529");
user_pref("media.gmp-manager.lastCheck", 1632533085);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1632173172);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.state.flash", 1);
user_pref("plugin.state.npmeadax", 2);
user_pref("sanity-test.device-id", "0x954f");
user_pref("sanity-test.driver-version", "8.970.100.9001");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20190912144529");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1632173172);
user_pref("toolkit.startup.last_success", 1632616941);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
